### ISSUE TITLE
!File causes errors in 107.0

### ISSUE THREAD

**Issue by JAAlperin** [thomasloven/hass-lovelace_gen#12] opened 2020-03-19 12:49 UTC
Moved resources from ui-lovelace.yaml to configure.yaml (via !include_dir_merge_list) for 107.  !file entries then causes parsing errors and Safe Mode.  When !file entries removed Lovelace seems to work properly.  I've put "# lovelace_gen" as first line in both the included yaml for resources and configuration.yaml.

Here's the log:
2020-03-19 08:44:48 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] could not determine a constructor for the tag '!file'
  in "/config/ui-lovelace_resources/ui-lovelace_resources.yaml", line 4, column 8
2020-03-19 08:44:48 ERROR (MainThread) [homeassistant.bootstrap] Failed to parse configuration.yaml: could not determine a constructor for the tag '!file'
  in "/config/ui-lovelace_resources/ui-lovelace_resources.yaml", line 4, column 8. Activating safe mode.

Want anything else?
Thank you Thomas.

**Comment by racoonx2p** [comment] 2020-03-21 06:56
I think this is duplicate of #11 . But I have the same issue. Only workaround so far is:
1) restart Home Asistent with commented sections where `- !include` is included. 
2) after that enable again sections with `- !include` 
3) reload lovelace with service `browser_mod.lovelace_reload`.

**Comment by bend** [comment] 2020-03-30 10:32
One of the workarounds I found is to include in the configuration.yaml all the Lovelace resources
I have a file containing all the Lovelace resources, and I include it in my configuration.yaml
This way you don't have to change your Lovelace configuration.

eg:

`lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
`

and lovelace/resources.yaml
```
 url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  type: js
- url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  type: module
....
```

**Comment by thomasloven** [comment] 2020-04-14 19:27
As mentioned in the readme, operation in the backed configuration cannot be guaranteed.

**Closed by thomasloven** 2020-04-14 19:27 UTC

**Comment by o0shojo0o** [comment] 2020-05-27 13:04
> One of the workarounds I found is to include in the configuration.yaml all the Lovelace resources
> I have a file containing all the Lovelace resources, and I include it in my configuration.yaml
> This way you don't have to change your Lovelace configuration every time you start homeassistant
> 
> eg:
> 
> ```
> 
> lovelace_gen:
> 
> lovelace:
>   mode: yaml
>   resources: !include lovelace/resources.yaml
> ```
> 
> and lovelace/resources.yaml
> 
> ```
>  url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
>   type: js
> - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
>   type: module
> ....
> ```

Thanks for the tip, it worked for me too!
